Evaluate CMS122 Against Patient Bundle
bulk-dqm/bulk-data-export-client pull request #2
Opened 2022-11-22 20:59 UTC by radamson

# Summary

Incredibly basic functionality demonstrating execution of CMS122 against a patient bundle using `fqm-execution` against possible. This implementation will need to evolve as we integrate it with the bulk-data client.

# Details

Adds `src/fqm.ts` which provides 3 new methods:
* `loadMeasureFromFile` - loads a measure from a json file present in `src/measures`
* `loadCMS122` - loads CMS122 using `loadMeasureFromFile`. In general, I don't like this method, but it seems reasonable while we only have one measure. Eventually we should encapsulate Measure management into a class (or at least memoize the file loading result).
* `evaluateCMS122ForPatient` - evaluates CMS122 against a patient bundle.

There are a few other changes included related to testing:
* Added a `jest.config.js` to enable `ts-jest`.
  * the `testMatch` attribute is only included so that tests in the build directory are not picked up. We could remove this because tests are no longer included in the build.
* Added a `test:coverage` script to `package.json` to collect test coverage metrics
* Updated `tsconfig` to exclude test files in the build. We could put our tests in another directory instead (this is [matter of opinion/taste](https://stackoverflow.com/questions/62442797/jest-folder-structure), but jest getting started docs include tests alongside code. :shrug:)

2022-11-28 16:05 UTC, sarahmcdougall requested changes
In regard to the testing setup, I’m used to having a separate directory for test files, but I think it makes sense to keep the tests alongside our code since we aren’t working with many files in `src` right now - we can always restructure things if it becomes unruly to have the tests alongside code. For now, though, the current approach looks good.

Something that warrants a larger discussion is the inclusion of ValueSets in the CMS122 measure bundle. There are licensing/legal issues behind checking in expanded ValueSets to Github, so I’m unsure about whether it’s plausible to have a `measures` directory with the measures we want to test against (this sounds a little hypocritical since fqm-execution currently has measure bundles checked in but we have it on the list of to-do’s to get rid of them - I actually just became aware of this licensing issue a few months ago). Even though the ecqm-content repositories include the measure bundles with ValueSets included, their licensing is likely different from ours. Maybe we should reach out to Sam to see if he has any insight on this since I do not know the specifics of ValueSet licensing in relation to ONC. If it turns out that we shouldn’t be committing the full CMS122 measure bundle, we can make a simplified test case for now to use with unit tests.

2022-11-28 16:05 UTC, sarahmcdougall commented on package.json
> +    "fqm-execution": "^1.0.0-rc.2",
fqm-execution version 1.0.1 is now available: [https://www.npmjs.com/package/fqm-execution/v/1.0.1](https://www.npmjs.com/package/fqm-execution/v/1.0.1)

I don't think there are any changes that would affect CMS122 measure calculation (most of the calculation-related changes are for ratio measures) but still worth updating to have the latest version

2022-11-28 16:05 UTC, sarahmcdougall commented on src/fqm.ts
> +import { CalculationOptions } from 'fqm-execution/build/types/Calculator';
```suggestion
import { Calculator, CalculatorTypes } from 'fqm-execution';
import * as path from 'path';
```
The `CalculationOptions` can be accessed by importing `CalculatorTypes` from fqm-execution (see in [README](https://github.com/projecttacoma/fqm-execution#typescript)). This looks like a cleaner approach to me since everything we need from fqm-execution is imported on one line

2022-11-28 16:05 UTC, sarahmcdougall commented on src/fqm.ts
> +export const evaluateCMS122ForPatient = async (patientBundle: fhir4.Bundle[], options: CalculationOptions = {}) => {
```suggestion
export const evaluateCMS122ForPatient = async (patientBundle: fhir4.Bundle[], options: CalculatorTypes.CalculationOptions = {}) => {
```
We'll need to make this change if we use the `CalculatorTypes` import

2022-11-30 14:24 UTC, radamson commented on package.json
> +    "fqm-execution": "^1.0.0-rc.2",
Good call - done!

2023-01-11 19:35 UTC, sarahmcdougall approved these changes
The added fixtures and updated functions/unit tests look good 👍 Good call on updating the README to node version 17 for now. The package.lock on this branch lists fqm-execution 1.0.2. [Version 1.0.3](https://github.com/projecttacoma/fqm-execution/releases/tag/v1.0.3) has been released so we should update the package-lock soon, but we can do that in one of the other open PRs so that this one gets merged and so that we have time to rebase all other branches before the Connectathon

2023-01-11 19:36 UTC, merged